### ISSUE TITLE
Where to get the gist_id from

### ISSUE THREAD

**Issue by jjasghar** [octopress/gist#4]
In gists now i see a SHA, something much larger than the small number all the examples say.

Is that correct? Can I add the https://gist.github.com/jjasghar/4172ba5697660441a26e or what should I use as the id?

I'm confused :disappointed: :panda_face:

**Comment by imathis** [comment]
I just tested the gist using the id `4172ba5697660441a26e` and it worked just fine. I suppose GitHub changed their gist id generator at some point. Gists made a while ago, got shorter ids.

![screenshot of safari 3-19-15 2 15 20 pm](https://cloud.githubusercontent.com/assets/12732/6738805/6461c8d4-ce42-11e4-87bb-2054127583fe.png)

**Comment by jjasghar** [comment]
Ah nice thanks! It's good to see you use dvorak too :) :beers: thanks for the great work!

**Comment by jjasghar** [comment]
Wow, i completely read that wrong, you just took my gist.

Heh, anyway, thanks!
